name: Bug Report
description: Help us fix bugs by providing your config and the issue details.
title: "[BUG] "
labels: [bug]
body:
  - type: textarea
    id: config
    attributes:
      label: Configuration Object
      description: |
        Please paste your configuration object here (JSON, JavaScript, or TypeScript).
        This helps us reproduce the issue exactly.
      placeholder: |
        {
          "production": {
            "rules": {
              "allow_disposable_emails": false
            }
          }
        }
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: What Happened?
      description: Describe the behavior or error you encountered.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen instead?
    validations:
      required: true
