name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: [bug]
body:
  - type: input
    id: environment
    attributes:
      label: Environment
      description: "E.g., production, development"
      placeholder: production
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: "Describe what happened"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Node.js
        - Browser
        - Other
    validations:
      required: true
